"""
CLI: take a backtest result JSON and emit a NinjaScript (.cs) skeleton
ready to paste into NinjaTrader 8's Strategy Analyzer for parity validation.

This is a *skeleton emitter* - it stubs out OnBarUpdate() with a TODO
matching the strategy name and parameters. Hand-tuning is still required;
full code generation will come in a later PR.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from textwrap import dedent

import click

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


NT8_TEMPLATE = dedent('''
    // Auto-generated by scripts/export_nt8_strategy.py
    // Source backtest: {source}
    // Strategy: {name}
    // Parameters: {params}
    //
    // Paste into NinjaTrader 8 -> New -> Strategy, then compile (F5).
    namespace NinjaTrader.NinjaScript.Strategies
    {{
        public class {class_name} : Strategy
        {{
            protected override void OnStateChange()
            {{
                if (State == State.SetDefaults)
                {{
                    Name        = "{class_name}";
                    Calculate   = Calculate.OnBarClose;
                    BarsRequiredToTrade = 50;
                }}
            }}

            protected override void OnBarUpdate()
            {{
                // TODO: port logic for "{name}" with parameters {params}.
                // Reference VectorBT implementation: src/strategies/{name}.py
            }}
        }}
    }}
''').strip() + "\n"


def _to_class_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_")) or "ExportedStrategy"


@click.command()
@click.option("--input", "input_path", required=True, type=click.Path(exists=True, dir_okay=False))
@click.option("--output", "output_path", required=True, type=click.Path(dir_okay=False))
def main(input_path: str, output_path: str) -> None:
    payload = json.loads(Path(input_path).read_text())
    strat = payload.get("strategy", {})
    name = strat.get("name", "exported")
    params = strat.get("params", {})

    code = NT8_TEMPLATE.format(
        source=input_path,
        name=name,
        params=json.dumps(params),
        class_name=_to_class_name(name),
    )
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(code)
    click.echo(f"Wrote NT8 skeleton -> {output_path}")


if __name__ == "__main__":
    main()
